pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)

    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = 'atlas-sdk-android'

include ':atlas-core'
include ':atlas-links'
include ':atlas-crash'
include ':atlas-crash-ndk'
// The sample app: the integration test, not published.
include ':sample'
